apiVersion: v1
kind: Service
metadata:
  name: java-app
  namespace: clients-demo
  labels:
    app: java-app
spec:
  selector:
    app: java-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
